const $=s=>document.querySelector(s),N=v=>Number(String(v??0).replace(/,/g,''))||0,M=n=>'₹'+Math.round(n).toLocaleString('en-IN'),E=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const D={party:[{Document:'D001',Name:'A G H AUTO',Budget:10000,PartyGrp:'4'},{Document:'D002',Name:'A G H MOTORS',Budget:'',PartyGrp:'4'},{Document:'D003',Name:'STAR AUTO',Budget:15000,PartyGrp:'7'}],sales:[{Document:'D001',Party:'A G H AUTO',ItemCode:'A100',ItemName:'Bearing A','Apr-26':6000,'May-26':11000},{Document:'D002',Party:'A G H MOTORS',ItemCode:'B200',ItemName:'Bearing B','Apr-26':3000,'May-26':2500},{Document:'D003',Party:'STAR AUTO',ItemCode:'A100',ItemName:'Bearing A','Apr-26':12000,'May-26':17000},{Document:'X999',Party:'IGNORED',ItemCode:'X','Apr-26':999999}],stock:[{ItemGroup:'Bearing',ItemCode:'A100',ItemDescription:'Bearing A',Unit:'PCS',ClosingQty:25,HORate:120},{ItemGroup:'Bearing',ItemCode:'B200',ItemDescription:'Bearing B',Unit:'PCS',ClosingQty:8,HORate:180}]};let d=D,months=[];
function go(){if($('#mobile').value!='9999999999'||$('#pin').value!='1234'){ $('#err').textContent='Use test login 9999999999 / 1234';return}$('#login').classList.add('hide');$('#app').classList.remove('hide');init()}
const docs=()=>new Set(d.party.map(x=>String(x.Document).trim())),valid=()=>d.sales.filter(x=>docs().has(String(x.Document).trim()));
function gb(g){let a=d.party.filter(x=>String(x.PartyGrp)==String(g)).map(x=>N(x.Budget)).filter(Boolean);return a.length?Math.max(...a):0}
function opt(el,a,label){el.innerHTML='<option value="">'+label+'</option>'+a.map(x=>'<option>'+E(x)+'</option>').join('')}
function init(){months=[...new Set(d.sales.flatMap(r=>Object.keys(r).filter(k=>/^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-\d{2}$/i.test(k))))];opt($('#customer'),[...new Set(d.party.map(x=>x.Name))],'All Customers');opt($('#group'),[...new Set(d.party.map(x=>x.PartyGrp))],'All PartyGrp');opt($('#month'),months,'All Months');['customer','group','month','item'].forEach(x=>$('#'+x).oninput=render);$('#sq').oninput=stock;render();stock()}
function render(){let c=$('#customer').value,g=$('#group').value,mo=$('#month').value,q=$('#item').value.toLowerCase(),ps=d.party.filter(p=>(!c||p.Name==c)&&(!g||String(p.PartyGrp)==g)),ad=new Set(ps.map(p=>String(p.Document))),rs=valid().filter(r=>ad.has(String(r.Document))&&(!q||String(r.ItemCode).toLowerCase().includes(q))),ms=mo?[mo]:months,total=rs.reduce((a,r)=>a+ms.reduce((b,m)=>b+N(r[m]),0),0),gs=[...new Set(ps.map(p=>p.PartyGrp))],bud=gs.reduce((a,x)=>a+gb(x),0)*ms.length;$('#sales').textContent=M(total);$('#budget').textContent=M(bud);$('#ach').textContent=bud?(total/bud*100).toFixed(1)+'%':'0%';$('#cust').textContent=ps.length;
$('#bt').innerHTML='<tr><th>Customer</th><th>PartyGrp</th>'+ms.map(m=>'<th>'+m+' Sales</th><th>'+m+' Budget</th><th>'+m+' Diff</th>').join('')+'</tr>'+ps.map(p=>{let pr=rs.filter(r=>String(r.Document)==String(p.Document)),b=gb(p.PartyGrp);return '<tr><td>'+E(p.Name)+'</td><td>'+E(p.PartyGrp)+'</td>'+ms.map(m=>{let s=pr.reduce((a,r)=>a+N(r[m]),0),x=s-b;return '<td class=num>'+M(s)+'</td><td class=num>'+M(b)+'</td><td class="num '+(x>=0?'pos':'neg')+'">'+M(x)+'</td>'}).join('')+'</tr>'}).join('');
let map={};rs.forEach(r=>{let k=r.ItemCode+'|'+r.ItemName;map[k]??={code:r.ItemCode,name:r.ItemName};ms.forEach(m=>map[k][m]=(map[k][m]||0)+N(r[m]))});$('#pt').innerHTML='<tr><th>Code</th><th>Item</th>'+ms.map(m=>'<th>'+m+'</th>').join('')+'<th>Total</th></tr>'+Object.values(map).map(x=>'<tr><td>'+E(x.code)+'</td><td>'+E(x.name)+'</td>'+ms.map(m=>'<td class=num>'+M(x[m]||0)+'</td>').join('')+'<td class=num>'+M(ms.reduce((a,m)=>a+(x[m]||0),0))+'</td></tr>').join('')}
function stock(){let q=$('#sq').value.toLowerCase(),r=d.stock.filter(x=>(x.ItemCode+' '+x.ItemDescription).toLowerCase().includes(q));$('#st').innerHTML='<tr><th>Group</th><th>Code</th><th>Description</th><th>Unit</th><th>Qty</th><th>HO Rate</th></tr>'+r.map(x=>'<tr><td>'+E(x.ItemGroup)+'</td><td>'+E(x.ItemCode)+'</td><td>'+E(x.ItemDescription)+'</td><td>'+E(x.Unit)+'</td><td>'+N(x.ClosingQty)+'</td><td>'+M(x.HORate)+'</td></tr>').join('')}