(()=>{"use strict";
const C=window.ALLIED_CONFIG,sb=supabase.createClient(C.SUPABASE_URL,C.SUPABASE_KEY),$=x=>document.getElementById(x),
mobileEmail=m=>String(m||"").replace(/\D/g,"")+"@allied.local",txt=v=>String(v??"").trim(),num=v=>{let n=Number(String(v??0).replace(/[,₹ ]/g,""));return isFinite(n)?n:0},money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(num(v)),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let S={session:null,profile:null,party:[],sales:[],stock:[],orders:[],users:[],months:[],month:"",group:"",doc:"",gpage:1,bpage:1,orderItems:[]};
function msg(e,t,ok=false){e.textContent=t||"";e.className="msg"+(ok?" success":"")}function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2800)}
function authView(id){["loadingScreen","loginScreen","recoveryScreen","appScreen"].forEach(x=>$(x).classList.toggle("hidden",x!==id))}
async function all(table){let out=[],a=0;while(1){let {data,error}=await sb.from(table).select("*").range(a,a+999);if(error)throw error;out.push(...data);if(data.length<1000)return out;a+=1000}}
function msort(a,b){let M={jan:0,feb:1,mar:2,apr:3,may:4,jun:5,jul:6,aug:7,sep:8,oct:9,nov:10,dec:11},f=x=>{let z=x.match(/^([A-Za-z]{3})-(\d{2,4})$/);if(!z)return 999999;let y=+z[2];if(y<100)y+=2000;return y*12+M[z[1].toLowerCase()]};return f(a)-f(b)}
async function boot(session){S.session=session;let {data:p,error}=await sb.from("profiles").select("*").eq("id",session.user.id).single();if(error)throw error;if(!p.is_active)throw Error("Account inactive. Contact Admin.");S.profile=p;await load();authView("appScreen");$("userName").textContent=p.full_name||session.user.email;$("userRole").textContent=p.role.toUpperCase();document.querySelectorAll(".adminOnly").forEach(e=>e.classList.toggle("hidden",p.role!=="admin"));document.querySelectorAll(".targetOnly").forEach(e=>e.classList.toggle("hidden",!(p.role==="admin"||p.target_access)));render();if(p.role==="admin")loadUsers()}
async function load(){[S.party,S.sales,S.stock]=await Promise.all([all("party_master"),all("sales_data"),all("stock")]);let set=new Set;S.sales.forEach(r=>Object.keys(r.month_sales||{}).forEach(m=>/^[A-Za-z]{3}-\d{2,4}$/.test(m)&&set.add(m)));S.months=[...set].sort(msort);if(!S.months.includes(S.month))S.month=S.months[0]||"";await loadOrders()}
function validSales(){let d=new Set(S.party.map(x=>txt(x.document)));return S.sales.filter(x=>d.has(txt(x.document)))}function parties(){return S.party.filter(x=>(!S.group||txt(x.party_grp)===S.group)&&(!S.doc||txt(x.document)===S.doc))}function sales(){let d=new Set(parties().map(x=>txt(x.document)));return validSales().filter(x=>d.has(txt(x.document)))}function sale(r){return S.month?num(r.month_sales?.[S.month]):S.months.reduce((a,m)=>a+num(r.month_sales?.[m]),0)}function gb(g){let a=S.party.filter(x=>txt(x.party_grp)===txt(g)).map(x=>num(x.budget)).filter(Boolean);return a.length?Math.max(...a):0}function mult(){return S.month?1:Math.max(1,S.months.length)}
function filters(){$("monthFilter").innerHTML='<option value="">All Months</option>'+S.months.map(x=>`<option>${esc(x)}</option>`).join("");$("monthFilter").value=S.month;let gs=[...new Set(S.party.map(x=>txt(x.party_grp)).filter(Boolean))].sort();$("groupFilter").innerHTML='<option value="">All Party Groups</option>'+gs.map(x=>`<option>${esc(x)}</option>`).join("");$("groupFilter").value=S.group;let ps=S.party.filter(x=>!S.group||txt(x.party_grp)===S.group);$("customerFilter").innerHTML='<option value="">All Customers</option>'+ps.map(x=>`<option value="${esc(x.document)}">${esc(x.name||x.document)}</option>`).join("");$("customerFilter").value=S.doc}
function kpis(){let p=parties(),s=sales().reduce((a,r)=>a+sale(r),0),gs=[...new Set(p.map(x=>txt(x.party_grp)).filter(Boolean))],b=gs.reduce((a,g)=>a+gb(g)*mult(),0);$("kSales").textContent=money(s);$("kBudget").textContent=money(b);$("kAch").textContent=(b?s/b*100:0).toFixed(1)+"%";$("kCustomers").textContent=p.length;$("kGroups").textContent=gs.length}
function paginate(a,page,size){if(size==="all")return{a,page:1,pages:1};size=+size||25;let pages=Math.max(1,Math.ceil(a.length/size));page=Math.min(page,pages);return{a:a.slice((page-1)*size,page*size),page,pages,total:a.length}}
function pager(id,o,fn){let e=$(id);e.innerHTML=`<span>${o.total??o.a.length} rows</span> `;if(o.pages>1)for(let i=1;i<=o.pages;i++)if(i===1||i===o.pages||Math.abs(i-o.page)<=2){let b=document.createElement("button");b.textContent=i;b.className=i===o.page?"active":"";b.onclick=()=>fn(i);e.appendChild(b)}}
function groups(){let p=parties(),vs=sales(),q=txt($("groupSearch").value).toLowerCase(),rows=[...new Set(p.map(x=>txt(x.party_grp)).filter(Boolean))].map(g=>{let d=new Set(p.filter(x=>txt(x.party_grp)===g).map(x=>txt(x.document))),s=vs.filter(x=>d.has(txt(x.document))).reduce((a,r)=>a+sale(r),0),b=gb(g)*mult();return{g,b,s,d:s-b,a:b?s/b*100:0}}).filter(x=>x.g.toLowerCase().includes(q));let o=paginate(rows,S.gpage,$("groupSize").value);S.gpage=o.page;$("groupBody").innerHTML=o.a.length?o.a.map(x=>`<tr><td><b>${esc(x.g)}</b></td><td>${money(x.b)}</td><td>${money(x.s)}</td><td class="${x.d>=0?"positive":"negative"}">${money(x.d)}</td><td>${x.a.toFixed(1)}%</td></tr>`).join(""):'<tr><td colspan=5>No data</td></tr>';pager("groupPager",o,p=>{S.gpage=p;groups()})}
function budgets(){let vs=sales(),q=txt($("budgetSearch").value).toLowerCase(),rows=parties().map(c=>{let s=vs.filter(r=>txt(r.document)===txt(c.document)).reduce((a,r)=>a+sale(r),0),b=gb(c.party_grp)*mult();return{n:c.name||c.document,g:c.party_grp,b,s,d:s-b}}).filter(x=>(txt(x.n)+" "+txt(x.g)).toLowerCase().includes(q));let o=paginate(rows,S.bpage,$("budgetSize").value);S.bpage=o.page;$("budgetBody").innerHTML=o.a.length?o.a.map(x=>`<tr><td>${esc(x.n)}</td><td>${esc(x.g)}</td><td>${money(x.b)}</td><td>${money(x.s)}</td><td class="${x.d>=0?"positive":"negative"}">${money(x.d)}</td></tr>`).join(""):'<tr><td colspan=5>No data</td></tr>';pager("budgetPager",o,p=>{S.bpage=p;budgets()})}
function products(){let map=new Map,q=txt($("productSearch").value).toLowerCase(),months=S.month?[S.month]:S.months;sales().forEach(r=>{let k=txt(r.item_code)+"|"+txt(r.item_name);if(!map.has(k))map.set(k,{c:r.item_code,n:r.item_name,m:{}});months.forEach(m=>map.get(k).m[m]=num(map.get(k).m[m])+num(r.month_sales?.[m]))});let rows=[...map.values()].filter(x=>(txt(x.c)+" "+txt(x.n)).toLowerCase().includes(q));$("productHead").innerHTML=`<tr><th>Item Code</th><th>Item Name</th>${months.map(m=>`<th>${esc(m)}</th>`).join("")}<th>Total</th></tr>`;$("productBody").innerHTML=rows.length?rows.map(x=>{let t=months.reduce((a,m)=>a+num(x.m[m]),0);return`<tr><td>${esc(x.c)}</td><td>${esc(x.n)}</td>${months.map(m=>`<td>${money(x.m[m])}</td>`).join("")}<td><b>${money(t)}</b></td></tr>`}).join(""):`<tr><td colspan="${3+months.length}">No data</td></tr>`}
function stock(){let q=txt($("stockSearch").value).toLowerCase(),a=S.stock.filter(x=>Object.values(x).some(v=>txt(v).toLowerCase().includes(q)));$("stockBody").innerHTML=a.map(x=>`<tr><td>${esc(x.item_group)}</td><td><b>${esc(x.item_code)}</b></td><td>${esc(x.item_description)}</td><td>${esc(x.unit)}</td><td>${num(x.closing_qty)}</td><td>${money(x.ho_rate)}</td></tr>`).join("")}
function render(){filters();kpis();groups();budgets();products();stock();renderOrders()}
async function loadOrders(){let {data,error}=await sb.from("sales_orders").select("*,sales_order_items(id)").order("created_at",{ascending:false});S.orders=error?[]:data}
function renderOrders(){$("ordersBody").innerHTML=S.orders.length?S.orders.map(x=>`<tr><td>${esc(x.order_no)}</td><td>${new Date(x.created_at).toLocaleString("en-IN")}</td><td>${esc(x.customer_name)}</td><td>${esc(x.party_grp)}</td><td>${esc(x.order_taken_by)}</td><td>${esc(x.status)}</td><td>${x.sales_order_items?.length||0}</td></tr>`).join(""):'<tr><td colspan=7>No orders</td></tr>'}
function nav(p){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(p).classList.remove("hidden");document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===p));if(p==="users")loadUsers()}
function openOrder(){S.orderItems=[];$("orderCustomer").innerHTML='<option value="">Select Customer</option>'+S.party.map(x=>`<option value="${esc(x.document)}">${esc(x.name||x.document)}</option>`).join("");$("orderItem").innerHTML='<option value="">Select Item</option>'+S.stock.map(x=>`<option value="${esc(x.item_code)}">${esc(x.item_code)} - ${esc(x.item_description)}</option>`).join("");$("orderBy").value=S.profile.full_name||S.session.user.email;$("orderGroup").value="";$("orderItemName").value="";$("orderRemark").value="";renderItems();$("orderModal").classList.remove("hidden")}
function renderItems(){$("orderItems").innerHTML=S.orderItems.length?S.orderItems.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.item_code)}</td><td>${esc(x.item_name)}</td><td>${x.qty}</td><td><button data-i="${i}" class="removeItem">Remove</button></td></tr>`).join(""):'<tr><td colspan=5>No items added</td></tr>';document.querySelectorAll(".removeItem").forEach(b=>b.onclick=()=>{S.orderItems.splice(+b.dataset.i,1);renderItems()})}
async function submitOrder(){let c=S.party.find(x=>txt(x.document)===txt($("orderCustomer").value));if(!c)return toast("Select customer.");if(!S.orderItems.length)return toast("Add at least one item.");let {data:o,error}=await sb.from("sales_orders").insert({user_id:S.session.user.id,document:c.document,customer_name:c.name||c.document,party_grp:c.party_grp,order_taken_by:S.profile.full_name||S.session.user.email,status:"Pending",remark:txt($("orderRemark").value)}).select().single();if(error)return toast(error.message);let z=await sb.from("sales_order_items").insert(S.orderItems.map(x=>({order_id:o.id,...x})));if(z.error)return toast(z.error.message);$("orderModal").classList.add("hidden");toast("Order submitted.");await loadOrders();renderOrders()}
async function excel(f){let b=await f.arrayBuffer(),w=XLSX.read(b,{type:"array"}),s=w.Sheets[w.SheetNames[0]];return XLSX.utils.sheet_to_json(s,{defval:"",raw:false})}function cell(r,n){let k=Object.keys(r).find(k=>n.map(x=>x.toLowerCase()).includes(txt(k).toLowerCase()));return k?r[k]:""}
async function upload(type){let file=$(type+"File").files[0],status=$(type+"Status");if(!file)return status.textContent="Select Excel file.";try{status.textContent="Uploading...";let raw=await excel(file),rows,fn;if(type==="party"){rows=raw.map(r=>({document:txt(cell(r,["Document"])),name:txt(cell(r,["Name"])),budget:num(cell(r,["Budget"])),party_grp:txt(cell(r,["PartyGrp"])),salesman:txt(cell(r,["Salesman"])),area:txt(cell(r,["Area"])),city:txt(cell(r,["City"])),mobile:txt(cell(r,["Mobile"])),segment:txt(cell(r,["Segment"])),order_value:num(cell(r,["Order"])),target:num(cell(r,["Target"]))})).filter(x=>x.document);fn="replace_party_master"}else if(type==="sales"){let ms=Object.keys(raw[0]||{}).filter(x=>/^[A-Za-z]{3}-\d{2,4}$/.test(txt(x)));rows=raw.map(r=>{let m={};ms.forEach(x=>m[x]=num(r[x]));return{party:txt(cell(r,["Party"])),mobile:txt(cell(r,["Mobile"])),main_grp:txt(cell(r,["MainGrp"])),item_code:txt(cell(r,["ItemCode"])),item_name:txt(cell(r,["ItemName"])),document:txt(cell(r,["Document"])),month_sales:m}});fn="replace_sales_data"}else{rows=raw.map(r=>({item_group:txt(cell(r,["ItemGroup"])),item_code:txt(cell(r,["ItemCode"])),item_description:txt(cell(r,["ItemDescription"])),unit:txt(cell(r,["Unit"])),closing_qty:num(cell(r,["ClosingQty"])),ho_rate:num(cell(r,["HORate"]))})).filter(x=>x.item_code);fn="replace_stock"}let {error}=await sb.rpc(fn,{p_rows:rows});if(error)throw error;status.textContent=`Success: ${rows.length} rows`;await load();render()}catch(e){status.textContent="Error: "+e.message}}
async function userApi(body){let {data:{session}}=await sb.auth.getSession(),r=await fetch(`${C.SUPABASE_URL}/functions/v1/${C.USER_FUNCTION}`,{method:"POST",headers:{apikey:C.SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok||j.success===false)throw Error(j.message||"User function error");return j}
async function loadUsers(){if(S.profile.role!=="admin")return;try{let j=await userApi({action:"list"});S.users=j.users||[];$("usersBody").innerHTML=S.users.map(u=>`<tr><td>${esc(u.full_name)}</td><td>${esc(u.mobile)}</td><td>${esc(u.role)}</td><td>${u.target_access?"Yes":"No"}</td><td>${u.is_active?"Active":"Inactive"}</td><td>${u.last_login?new Date(u.last_login).toLocaleString("en-IN"):"-"}</td><td><button class="editUser" data-id="${u.id}">Edit</button> <button class="pwdUser" data-id="${u.id}">Password</button> <button class="delUser" data-id="${u.id}">Delete</button></td></tr>`).join("");document.querySelectorAll(".editUser").forEach(b=>b.onclick=()=>editUser(b.dataset.id))}catch(e){toast(e.message)}}
function editUser(id){let u=S.users.find(x=>x.id===id);$("editUserId").value=id;$("uName").value=u.full_name||"";$("uMobile").value=u.mobile||"";$("uPassword").value="";$("uRole").value=u.role;$("uTarget").value=String(u.target_access);$("uStatus").value=String(u.is_active);$("statusBox").classList.remove("hidden");$("userModalTitle").textContent="Edit User";$("userModal").classList.remove("hidden")}
async function saveUser(){try{let id=txt($("editUserId").value),p={action:id?"update":"create",full_name:txt($("uName").value),mobile:txt($("uMobile").value),role:$("uRole").value,target_access:$("uTarget").value==="true"};if(id){p.user_id=id;p.is_active=$("uStatus").value==="true";if($("uPassword").value)p.password=$("uPassword").value}else{p.email=mobileEmail(mobile);p.password=$("uPassword").value;if(p.password.length<6)throw Error("Password minimum 6 characters.")}await userApi(p);$("userModal").classList.add("hidden");toast("User saved.");loadUsers()}catch(e){msg($("userMessage"),e.message)}}
function events(){
$("loginForm").onsubmit=async e=>{e.preventDefault();msg($("loginMessage"),"");let mobile=txt($("loginMobile").value).replace(/\D/g,"");if(mobile.length<10)return msg($("loginMessage"),"Valid mobile number enter karo.");let {data,error}=await sb.auth.signInWithPassword({email:mobileEmail(mobile),password:$("loginPassword").value});if(error)return msg($("loginMessage"),error.message);try{await boot(data.session);await sb.from("profiles").update({last_login:new Date().toISOString()}).eq("id",data.session.user.id)}catch(x){msg($("loginMessage"),x.message);authView("loginScreen")}};
$("togglePassword").onclick=()=>{let i=$("loginPassword");i.type=i.type==="password"?"text":"password";$("togglePassword").textContent=i.type==="password"?"Show":"Hide"};
$("recoveryForm").onsubmit=async e=>{e.preventDefault();let p=$("newPassword").value;if(p.length<6)return msg($("recoveryMessage"),"Minimum 6 characters.");if(p!==$("confirmPassword").value)return msg($("recoveryMessage"),"Passwords do not match.");let {error}=await sb.auth.updateUser({password:p});if(error)return msg($("recoveryMessage"),error.message);msg($("recoveryMessage"),"Password updated successfully.",true);await sb.auth.signOut();history.replaceState({},document.title,location.pathname);setTimeout(()=>authView("loginScreen"),600)};
$("logoutBtn").onclick=async()=>{await sb.auth.signOut();authView("loginScreen")};document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>nav(b.dataset.page));
$("monthFilter").onchange=()=>{S.month=$("monthFilter").value;render()};$("groupFilter").onchange=()=>{S.group=$("groupFilter").value;S.doc="";render()};$("customerFilter").onchange=()=>{S.doc=$("customerFilter").value;let c=S.party.find(x=>txt(x.document)===S.doc);if(c)S.group=txt(c.party_grp);render()};$("resetFilters").onclick=()=>{S.month=S.months[0]||"";S.group=S.doc="";render()};
$("groupSearch").oninput=groups;$("budgetSearch").oninput=budgets;$("productSearch").oninput=products;$("stockSearch").oninput=stock;$("groupSize").onchange=()=>{S.gpage=1;groups()};$("budgetSize").onchange=()=>{S.bpage=1;budgets()};
document.querySelectorAll(".openOrder").forEach(b=>b.onclick=openOrder);document.querySelectorAll(".closeOrder").forEach(b=>b.onclick=()=>$("orderModal").classList.add("hidden"));$("orderCustomer").onchange=()=>{let c=S.party.find(x=>txt(x.document)===txt($("orderCustomer").value));$("orderGroup").value=c?.party_grp||""};$("orderItem").onchange=()=>{let x=S.stock.find(s=>txt(s.item_code)===txt($("orderItem").value));$("orderItemName").value=x?.item_description||""};$("addItem").onclick=()=>{let x=S.stock.find(s=>txt(s.item_code)===txt($("orderItem").value)),q=num($("orderQty").value);if(!x||q<=0)return toast("Select item and Qty.");let e=S.orderItems.find(i=>txt(i.item_code)===txt(x.item_code));e?e.qty+=q:S.orderItems.push({item_code:x.item_code,item_name:x.item_description,qty:q});renderItems()};$("clearOrder").onclick=()=>{S.orderItems=[];renderItems()};$("submitOrder").onclick=submitOrder;
$("uploadParty").onclick=()=>upload("party");$("uploadSales").onclick=()=>upload("sales");$("uploadStock").onclick=()=>upload("stock");
$("addUserBtn").onclick=()=>{$("editUserId").value="";$("uName").value=$("uMobile").value=$("uPassword").value="";$("uRole").value="user";$("uTarget").value="true";$("statusBox").classList.add("hidden");$("userModalTitle").textContent="Add User";$("userModal").classList.remove("hidden")};document.querySelectorAll(".closeUser").forEach(b=>b.onclick=()=>$("userModal").classList.add("hidden"));$("saveUser").onclick=saveUser}
async function init(){events();let {data:{session}}=await sb.auth.getSession();if(location.hash.includes("type=recovery")||location.search.includes("type=recovery"))return authView("recoveryScreen");if(!session)return authView("loginScreen");try{await boot(session)}catch(e){await sb.auth.signOut();authView("loginScreen");msg($("loginMessage"),e.message)}}
sb.auth.onAuthStateChange((event,session)=>{if(event==="PASSWORD_RECOVERY"){S.session=session;authView("recoveryScreen")}});
init();
})();